### ISSUE TITLE
Project not published to npm

### ISSUE THREAD

**Issue by gusfune** [payloadcms/plugin-sentry#3]
It seems the project is not yet publicly released in NPM: https://www.npmjs.com/package/@payloadcms/plugin-sentry

This causes installation error of the package:
```
➤ YN0027: @payloadcms/plugin-sentry@unknown can't be resolved to a satisfying range
➤ YN0035: The remote server failed to provide the requested resource
➤ YN0035:   Response Code: 404 (Not Found)
➤ YN0035:   Request Method: GET
➤ YN0035:   Request URL: https://registry.yarnpkg.com/@payloadcms%2fplugin-sentry
```

**Comment by JessRynkar** [comment]
Hey @gusfune my apologies I didn't make it clear that this repo was still a WIP, I'll be buttoning it up and publishing this week so I'll ping you when it's ready to use 👍

**Comment by JessRynkar** [comment]
@gusfune Happy Friday, this plugin is officially published to [npm](https://www.npmjs.com/package/@payloadcms/plugin-sentry) 🎉
