### ISSUE TITLE
Access to Sentry options (e.g. captureMessages...)

### ISSUE THREAD

**Issue by TomBell95** [payloadcms/plugin-sentry#5]
Is it possible to directly call options such as `captureMessage` or `captureException`? Its great that the logging is built in, but would be good to have the freedom of logging to Sentry where we need to. 

## Example
```javascript
import * as Sentry from '@sentry/nextjs'

Sentry.captureMessage(msg, {
  level: 'info',
  extra: {
    info: stringifyData(info),
  },
})
```

https://docs.sentry.io/platforms/javascript/usage/

Thanks!

**Comment by TomBell95** [comment]
@JessChowdhury Apologies for tagging you directly, but would you have any recommendations for this please?

**Comment by JessRynkar** [comment]
Hey @TomBell95, I'm looking into what is possible here and will get back to you shortly.

**Comment by TomBell95** [comment]
Thanks, appreciate it !

**Comment by JessRynkar** [comment]
@TomBell95 Thank you for your patience! Looping back, I can confirm that `Sentry.captureMessage` and `Sentry.captureException` work as expected when they are used inside Payload collection or field hooks. You'll still need to import them of course.

To send Sentry data from the admin panel, you'll need a custom component wrapped with the `<Sentry.ErrorBoundary>` which can be imported from `import * as Sentry from '@sentry/react'`.

If this doesn't cover your use case, let me know where would you be looking to fire `Sentry.captureMessage` and I'll take a look at how to set it up.

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-sentry) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. But feel free to [open a new discussion](https://github.com/payloadcms/payload/discussions) around this, or even [hop on our Discord](https://discord.com/invite/payload) and get help there.
