### ISSUE TITLE
Test errors component is pushed on dashboard

### ISSUE THREAD

**Issue by treturner** [payloadcms/plugin-sentry#7]
![image](https://github.com/payloadcms/plugin-sentry/assets/16762066/c6bd6ba2-04df-4baa-93ed-cc07e619d591)

Small detail, after updating the plugin to use with Payloadcms 2.0, this test errors component is pushed onto the dashboard.

**Comment by treturner** [comment]
I opened a PR that comments out the config that is injecting into the dashboard #9

**Comment by jacobsfletch** [comment]
Thank you @treturner! I left a comment in your PR just now.

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-sentry) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. But feel free to [open a new discussion](https://github.com/payloadcms/payload/discussions) around this, or even [hop on our Discord](https://discord.com/invite/payload) and get help there.
